OPTICAL_DEFAULTS = {
    "enabled": False,
    "genieacs": {
        "base_url": "http://genieacs:7557",
        "username": "",
        "password": "",
        "page_size": 100,
    },
    "telegram": {
        "bot_token": "",
        "chat_id": "",
    },
    "optical": {
        "rx_threshold_dbm": -26.0,
        "tx_low_threshold_dbm": -1.0,
        "priority_rx_threshold_dbm": -29.0,
        "rx_paths": [
            "InternetGatewayDevice.WANDevice.1.X_CMCC_EponInterfaceConfig.RXPower",
            "InternetGatewayDevice.WANDevice.1.X_CMCC_GponInterfaceConfig.RXPower",
            "InternetGatewayDevice.WANDevice.1.X_FH_GponInterfaceConfig.RXPower",
            "InternetGatewayDevice.WANDevice.1.X_GponInterafceConfig.RXPower",
            "InternetGatewayDevice.WANDevice.1.X_GponInterfaceConfig.RXPower",
            "InternetGatewayDevice.WANDevice.1.X_CT-COM_EponInterfaceConfig.RXPower",
            "VirtualParameters.RXPower",
        ],
        "tx_paths": [
            "InternetGatewayDevice.WANDevice.1.X_CMCC_EponInterfaceConfig.TXPower",
            "InternetGatewayDevice.WANDevice.1.X_FH_GponInterfaceConfig.TXPower",
            "InternetGatewayDevice.WANDevice.1.X_GponInterafceConfig.TXPower",
            "InternetGatewayDevice.WANDevice.1.X_GponInterfaceConfig.TXPower",
            "InternetGatewayDevice.WANDevice.1.X_CT-COM_EponInterfaceConfig.TXPower",
            "VirtualParameters.TXPower",
        ],
        "pppoe_paths": [
            "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection.1.Username",
            "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection.1.X_BROADCOM_COM_Username",
            "VirtualParameters.pppoeUsername",
        ],
        "ip_paths": [
            "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection.1.ExternalIPAddress",
            "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress",
            "VirtualParameters.pppoeIP",
        ],
    },
    "general": {
        "message_title": "Optical Power Alert",
        "include_header": True,
        "max_chars": 3800,
        "schedule_time_ph": "07:00",
        "timezone": "Asia/Manila",
    },
}

RTO_DEFAULTS = {
    "enabled": False,
    "ssh": {
        "host": "",
        "port": 22,
        "user": "",
        "password": "",
        "use_key": False,
        "key_path": "",
        "remote_csv_path": "/opt/libreqos/src/ShapedDevices.csv",
    },
    "telegram": {
        "bot_token": "",
        "chat_id": "",
    },
    "ping": {
        "count": 5,
        "per_ping_timeout_sec": 1,
        "max_workers": 64,
    },
    "general": {
        "message_title": "RTO Customers",
        "include_header": True,
        "output_mode": "split",
        "max_chars": 3800,
        "max_lines": 200,
        "top_n": 20,
        "ping_interval_minutes": 5,
        "schedule_time_ph": "07:00",
        "timezone": "Asia/Manila",
    },
    "history": {
        "window_size": 30,
    },
    "storage": {
        "raw_retention_days": 30,
    },
    "classification": {
        "issue_rto_pct": 5.0,
        "issue_streak": 2,
        "stable_rto_pct": 1.0,
    },
}

ISP_PING_DEFAULTS = {
    "enabled": False,
    "telegram": {
        "bot_token": "",
        "pulsewatch_bot_token": "",
        "command_bot_token": "",
        "chat_id": "",
        "command_chat_id": "",
        "alert_channel_id": "",
        "allowed_user_ids": [],
        "command_feedback_seconds": 10,
    },
    "general": {
        "ping_timeout_seconds": 1,
        "ping_count": 5,
        "max_parallel_pings": 8,
        "daemon_interval_seconds": 15,
        "include_up_icmp": False,
        "up_icmp_lines": 5,
        "down_reminder_hours": 8,
    },
    "report": {
        "daily_time": "07:00",
        "timezone": "Asia/Manila",
    },
    "targets": [],
    "pulsewatch": {
        "enabled": False,
        "manage_address_lists": False,
        "reconcile_interval_minutes": 10,
        "store_raw_output": False,
        "retention_days": 30,
        "rollup_retention_days": 365,
        "list_presets": [],
        "mikrotik": {
            "cores": [],
        },
        "speedtest": {
            "enabled": False,
            "min_interval_minutes": 60,
            "command": "speedtest",
            "args": "--format=json",
            "use_netns": False,
            "netns_prefix": "isp",
        },
        "ping": {
            "timeout_seconds": 1,
            "count": 5,
            "max_parallel": 8,
            "interval_seconds": 1,
        },
        "dashboard": {
            "default_target": "all",
            "refresh_seconds": 2,
            "loss_history_minutes": 120,
            "pie_default_days": 7,
        },
        "stability": {
            "stable_max_ms": 80,
            "unstable_max_ms": 150,
            "down_source": "wan",
        },
        "isps": [
            {
                "id": "isp1",
                "label": "ISP 1",
                "source_ip": "",
                "core2_source_ip": "",
                "core3_source_ip": "",
                "sources": {},
                "router_scope": "both",
                "ping_router": "auto",
                "ping_core_id": "auto",
                "ping_targets": ["1.1.1.1", "8.8.8.8"],
                "thresholds": {
                    "latency_ms": 120,
                    "loss_pct": 20,
                },
                "consecutive_breach_count": 3,
                "cooldown_minutes": 10,
            },
            {
                "id": "isp2",
                "label": "ISP 2",
                "source_ip": "",
                "core2_source_ip": "",
                "core3_source_ip": "",
                "sources": {},
                "router_scope": "both",
                "ping_router": "auto",
                "ping_core_id": "auto",
                "ping_targets": ["1.1.1.1", "8.8.8.8"],
                "thresholds": {
                    "latency_ms": 120,
                    "loss_pct": 20,
                },
                "consecutive_breach_count": 3,
                "cooldown_minutes": 10,
            },
            {
                "id": "isp3",
                "label": "ISP 3",
                "source_ip": "",
                "core2_source_ip": "",
                "core3_source_ip": "",
                "sources": {},
                "router_scope": "both",
                "ping_router": "auto",
                "ping_core_id": "auto",
                "ping_targets": ["1.1.1.1", "8.8.8.8"],
                "thresholds": {
                    "latency_ms": 120,
                    "loss_pct": 20,
                },
                "consecutive_breach_count": 3,
                "cooldown_minutes": 10,
            },
            {
                "id": "isp4",
                "label": "ISP 4",
                "source_ip": "",
                "core2_source_ip": "",
                "core3_source_ip": "",
                "sources": {},
                "router_scope": "both",
                "ping_router": "auto",
                "ping_core_id": "auto",
                "ping_targets": ["1.1.1.1", "8.8.8.8"],
                "thresholds": {
                    "latency_ms": 120,
                    "loss_pct": 20,
                },
                "consecutive_breach_count": 3,
                "cooldown_minutes": 10,
            },
            {
                "id": "isp5",
                "label": "ISP 5",
                "source_ip": "",
                "core2_source_ip": "",
                "core3_source_ip": "",
                "sources": {},
                "router_scope": "both",
                "ping_router": "auto",
                "ping_core_id": "auto",
                "ping_targets": ["1.1.1.1", "8.8.8.8"],
                "thresholds": {
                    "latency_ms": 120,
                    "loss_pct": 20,
                },
                "consecutive_breach_count": 3,
                "cooldown_minutes": 10,
            },
        ],
    },
}

WAN_PING_DEFAULTS = {
    "enabled": False,
    "telegram": {
        "bot_token": "",
        "chat_id": "",
    },
    "general": {
        "interval_seconds": 30,
    },
    "wans": [],
    "pppoe_routers": [],
    "messages": {},
}

WAN_MESSAGE_DEFAULTS = {
    "down_msg": "🔴 {label} {target} is DOWN {{datetime}} 😢😤",
    "up_msg": "🟢 {label} {target} is UP {{datetime}}\n  Target: {target}\n  Source: {local-ip}\n  {ping5}",
    "still_down_msg": "🔴 {label} {target} is still DOWN {down-sincedatetime}",
}

WAN_SUMMARY_DEFAULTS = {
    "enabled": False,
    "daily_time": "07:00",
    "all_up_msg": "All ISP UP {up}/{total}",
    "partial_msg": "Partial ISP down {up}/{total}",
    "line_template": "{label} Status {status}!",
}
